### PR TITLE
Add `singlesketch` command

### PR DESCRIPTION
**Pull request by mr-eyes**
This PR adds the `singlesketch` command to directly sketch a FASTA or stdin to resemble the regular `sourmash sketch` command.

### CODE REVIEW

**Comment by mr-eyes** [comment]
Ready for review @ctb @bluegenes

**Review by ctb — APPROVED** [review]
Lovely work!

**Comment by mr-eyes** [comment]
@ctb Thank you!! Ready to merge whenever:)

**Comment by bluegenes** [comment]
wait! no, `moltype` needs to be fixed: the moltype that is needed at the beginning of sketching is actually the input moltype, not the sketch moltype -- i.e. is the FASTA file DNA or protein? I think an --input-moltype param might be needed.

@ctb @mr-eyes

**Pull request merged**
