### PR TITLE
Set up pixi for development environment

### PR DESCRIPTION
**Pull request by luizirber**
- Set up pixi configs in `pyproject.toml`, mirroring the ones from sourmash
- Add dev docs on how to use pixi

Not sure if replace or keep as separate section in docs...

### CODE REVIEW

**Comment by ctb** [comment]
Tried this out, ran into this error:
```
  × default: error installing/updating PyPI dependencies
  ├─▶ Failed to prepare distributions                                             ├─▶ Failed to fetch wheel: scipy==1.14.1                                        ╰─▶ Build backend failed to build wheel through `build_wheel()` with exit 
```

mind you, I did this after deactivating mamba and everything. But, actually, it failed within my normal dev environment.

Any ideas? 

```
% uname -a
Darwin Titus-MacBook-tsalmoth.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103 arm64
```

**Comment by ctb** [comment]
on farm, it is taking multiple days to install gcc. 😭  restarting in case there was a disk hang or something.

Screenshot 2024-10-22 at 7 05 25 AM

**Comment by luizirber** [comment]
> Tried this out, ran into this error:
> 
> ```
>   × default: error installing/updating PyPI dependencies
>   ├─▶ Failed to prepare distributions                                             ├─▶ Failed to fetch wheel: scipy==1.14.1                                        ╰─▶ Build backend failed to build wheel through `build_wheel()` with exit 
> ```
> 
> mind you, I did this after deactivating mamba and everything. But, actually, it failed within my normal dev environment.
> 
> Any ideas?

wow, this one was trying to COMPILE SCIPY FROM SOURCE. Who does that in 2024?

I added `sourmash-minimal` as an explicit dep (so it pulls scipy from conda-forge), this is likely an upstream bug but works for now in macOS. Can you try latest commit?

**Comment by ctb** [comment]
working well on my Mac. Trying on farm (linux).

**Comment by luizirber** [comment]
> on farm, it is taking multiple days to install gcc. 😭 restarting in case there was a disk hang or something.

Your home dir is likely NFS? pixi (and Rust) can be a bit overwhelming for NFS, both create a lot of files (for env and compilation)

**Comment by ctb** [comment]
on farm, still downloading gcc...

What's the debugging approach you're using to dig in?

**Comment by luizirber** [comment]
> on farm, still downloading gcc...
> 
> What's the debugging approach you're using to dig in?

I was able to run it on farm, is there a chance your home dir is full?

**Comment by ctb** [comment]
it's not full...

**Comment by ctb** [comment]
trying from scratch: `pixi clean`

**Comment by ctb** [comment]
It's still running on farm. I have no idea why you are getting different results from me.

Screenshot 2024-10-24 at 6 53 22 AM

**Review by ctb — APPROVED** [review]

**Comment by luizirber** [comment]
> All works! 3.9 GB install in the `.pixi` directory tho ;)

Yeah, conda packages can be gargantuan. Rust compiler alone is ~500MB... Luckily it is a build dependency, so people using sourmash and plugins don't have to install it, but for dev... it is a requirement =]

**Pull request merged**
