### PR TITLE
MRG: write full gather result from `fastgather` and non-rocksdb `fastmultigather`

### LINKED ISSUE #287: `fastmultigather` should report full gather results for non rocksdb databases!
ref https://github.com/sourmash-bio/sourmash/issues/3095

I don't think there's any real impediment, just needs to happen! :)

### PR DESCRIPTION
**Pull request by bluegenes**
This PR adds utilities for building full gather results file for `fastgather` and non-rocksdb `fastmultigather`, and makes full output default.

- Fixes #287 
- Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/187
- Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/254
- includes a local fix for https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/318, which means that the `fastgather` and **non-rocksdb** `fastmultigather` full output here matches sourmash gather. Issues with rocksdb gather are being handled elsewhere.

## Benchmarking

| software/version | command | details | time | max RAM |
| -------- | -------- | -------- | -- | -- |
| branchwater v0.9.3 | `fastgather` | minimal result | <span style="color:green">**1m 47s**</span> | <span style="color:black">**14 GB**</span> |
| branchwater v0.9.3-dev | `fastgather` | full result | <span style="color:green">**1m 57s**</span> | <span style="color:black">**14 GB**</span> |
| branchwater v0.9.3 | `fastmultigather` | minimal result | <span style="color:red">**8m 3s**</span> | <span style="color:black">**25 GB**</span> |
| branchwater v0.9.3-dev | `fastmultigather` | full result | <span style="color:red">**8m 9s**</span> | <span style="color:black">**25 GB**</span> |
| branchwater v0.9.3 | `fastmultigather` | rocksdb full result | <span style="color:green">**24s**</span> | <span style="color:green">**600 MB**</span> |

progress/separate PRs:
- [x] Fill out `match_filename` in full results (https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/303; requires new sourmash core release with https://github.com/sourmash-bio/sourmash/pull/3121)
- [x] switch to using `KmerMinHashBTree` for hash subtraction +benchmark. Per luiz, `KmerMinHashBTree` are better for any situation where we'll be subtracting/adding hashes to a sketch https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/310
- [x] sourmash: make getting `Record`.filename public in order to keep match_filename and write it to full results. (https://github.com/sourmash-bio/sourmash/pull/3121)
- [x] remove --full-results and make full results default #327

### CODE REVIEW

**Comment by bluegenes** [comment]
hackmd version: https://hackmd.io/IgakZLceRyeTCXuCgH0iDA?edit

benchmarking with this branch: 

| software/version | command | details | time | max RAM |
| -------- | -------- | -------- | -- | -- |
| branchwater v0.9.3 | `fastgather` | minimal result | <span style="color:green">**2m 23s**</span> | <span style="color:black">**14 GB**</span> |
| branchwater v0.9.3 | `fastgather` | full result | <span style="color:green">**1m 57s**</span> | <span style="color:black">**14 GB**</span> |
| branchwater v0.9.3 | `fastmultigather` | minimal result | <span style="color:red">**8m 14s**</span> | <span style="color:black">**25 GB**</span> |
| branchwater v0.9.3 | `fastmultigather` | full result | <span style="color:red">**8m 9s**</span> | <span style="color:black">**25 GB**</span> |
| branchwater v0.9.3 | `fastmultigather` | rocksdb full result | <span style="color:green">**24 s**</span> | <span style="color:green">**600 MB**</span> |

**Comment by bluegenes** [comment]
@ctb ready for review.

Note: When I did column-by-column comparisons with python-based sourmash gather, the `remaining_bp` entries do not match. Can you see anything I'm doing wrong? I think the calculation here may actually be correct?

**Comment by ctb** [comment]
A few notes and questions - 

* if I infer correctly, the results of sourmash gather are in `SRR606249.x.gtdb-rs214.gather.csv`, yes?
* this PR sets the output columns to be `{'match_name', 'match_filename', 'match_md5'}` rather than `{'name', 'filename', 'md5'}`, right?

**Comment by ctb** [comment]
when I look at the differences in the matching names between `srr.fg.full.csv` and `SRR606249.x.gtdb-rs214.gather.csv`, I see:

Screenshot 2024-05-01 at 4 43 04 PM

To me this looks like it's simply the difference between different implementations of the underlying gather algorithm: there are different matches, but they're all the same species, so I bet there is a tie at some point and `sourmash gather` decides differently from `fastgather`.

See https://github.com/ctb/2024-debug-gather-difference for notebook for exploring the differences.

**Comment by ctb** [comment]
I think the column name update is good, per https://github.com/sourmash-bio/sourmash/issues/1555, since we want to use the prefetch-like column names. Just, y'know, we should put them in the PR description and also document it.

I'll look at the set of column names here and see if there's something else we should change here in prep for sourmash v5.

**Comment by ctb** [comment]
> Just looking at the number of lines in the gather result:
> 
> ```
>      85 SRR606249.gather.csv
>      85 SRR606249.x.gtdb-rs214.gather.csv
>      85 srr.fg.csv
>      85 srr.fg.full.csv
>      79 srr.fmg-rdb.csv
> ```
> ... so rocksdb fastmultigather produces 79 result lines, while the rest had 85 🤔

Actually, I'm finding (on a stripped-down subset of 90 sketches that contains the union of all matches across the various CSVs) that my newly generated `srr.fmg.csv` only has 79 matches. You missed including it in the table above, too, but your CSV `srr.fmg.csv` also only has 79 matches.

That suggests that maybe fastmultigather is the problem, not rocksdb.

**Comment by ctb** [comment]
I see the same 79-line output from fastmultigather against my `combined-matches-k31.sig.zip` whether I use rocksdb or the zipfile, so I have a small, reproducible example of the differences. 🎉 . Will commence the digging!

**Comment by ctb** [comment]
> That suggests that maybe fastmultigather is the problem, not rocksdb.

ok, I'm wrong, because of the way fastmultigather -o works. Digging in more.

**Comment by ctb** [comment]
Debugged one mismatch here: https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/318 - this was causing `f_unique_to_query` to be incorrectly calculated in the Rust code.

Fixed by https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/319, which can be merged into this PR.

There's another set of mismatches occurring from the same error in the RocksDB code, which uses sourmash-rs core code to calculate `f_unique_to_query` - see https://github.com/sourmash-bio/sourmash/issues/3137, and a fix in https://github.com/sourmash-bio/sourmash/pull/3138.

And there's an additional discrepancy in the RocksDB-based fastmultigather, as noted above. I've zeroed in on one specific problem that shows up when looking at gather results (from Python, or fastgather, for fastmultigather against a sig list ;). In brief, the 12th match in RocksDB-fastmultigather is returning too small an overlap. I can spend more time debugging this in the future, but it suggests to me that something is rotten in `RevIndex::gather`.

Screenshot 2024-05-04 at 1 23 56 PM

**Comment by ctb** [comment]
Random additional thought - is there any reason not to make `--full-results` the default, given that there seems to be no significant extra processing cost?

**Comment by bluegenes** [comment]
> Random additional thought - is there any reason not to make `--full-results` the default, given that there seems to be no significant extra processing cost?
> 
> That change would also fix #254

Yes, we can do that. I set it up this way b/c you were originally concerned about slowdown :)

**Comment by ctb** [comment]
> Yes, we can do that. I set it up this way b/c you were originally concerned about slowdown :)

and I appreciate it, but I think you've done a great job of showing that that's not a concern!

**Comment by ctb** [comment]
some things to do before merge - 

* put benchmarks in top level description
* if it does fix https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/254, indicate as such in top level description
* reference https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/318 and rocksdb breakage stuff in top level description

**Comment by bluegenes** [comment]
> some things to do before merge -
> 
> * put benchmarks in top level description
> * if it does fix [`fastgather` CSV output for `intersect_bp` is in hashes, not in hashes * scaled as it is in `sourmash gather` output #254](https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/254), indicate as such in top level description
> * reference [fastmultigather returns different results from sourmash gather in Python, in PR #298 #318](https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/318) and rocksdb breakage stuff in top level description

done! ready for re-review, etc

**Review by ctb — APPROVED** [review]
I ran some separate validation scripts and it all looks great! Thank you!! It's a go for merge!

**Pull request merged**
