### PR TITLE
MRG: update to (prospective) sourmash r0.18.0

### PR DESCRIPTION
**Pull request by ctb**
This PR updates to sourmash core latest, which will be r0.18.0.

The biggest set of changes in the plugin relate to https://github.com/sourmash-bio/sourmash/pull/3431, which made it possible to detect bad (and good) zip files based on content, and handle the error; in particular, this means that we can continue past errors from reading a file misnamed as a sig zip file, and try reading it in other ways. So a bunch of tests (e.g. `test_fastgather.py::test_bad_against_3`) no longer apply!

sourmash r0.18.0 also includes https://github.com/sourmash-bio/sourmash/pull/3434, which changes the behavior of `Signature::name()` to return an `Option` if `name` is not set, rather than defaulting to either `filename()` or `md5sum()`, in that order. This caused a bug (see https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/538#issuecomment-2543882346, split out into https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/550) where manifests would improperly disagree about whether two `Record`s matched. 

Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/550

TODO:
- [x] add test for manifest intersection per https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/550
- [x] should we add back a test for a misnamed zip file?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review & merge @bluegenes! But I will merge this w/o a review as needed in the interest of getting https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/531 into a release ;).

**Review by bluegenes — APPROVED** [review]
Lgtm

**Comment by bluegenes** [comment]
We still have a test for improper zip file that can't be read, right?

**Comment by ctb** [comment]
Uhh... actually, good question. Probably. What kind(s) of things are you thinking about? I could see -

* zip file that is corrupted
* zip file that doesn't have a manifest

other things?

**Comment by bluegenes** [comment]
Yep -- I was mostly thinking about zipfiles that get interrupted while writing and thus can't be read - I guess this falls into your "corrupted" category. The error is now propagated from sourmash, so I'm guessing we just exit and say we can't load the sigs. 

Just wanted to make sure we still have a test covering this.

**Pull request merged**
